# Generated by Django 4.0.5 on 2022-06-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAndCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('element_type', models.CharField(choices=[('CATEGORY', 'Category'), ('SALES', 'Sales')], max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.saleandcategory', to_field='uuid')),
            ],
        ),
    ]
