# Generated by Django 4.0.5 on 2022-06-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleandcategory',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
