# Generated by Django 4.0.5 on 2022-06-16 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_rename_parent_id_saleandcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAndCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('element_type', models.CharField(choices=[('CATEGORY', 'Category'), ('OFFER', 'Offer')], max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.offerandcategory', to_field='uuid')),
            ],
        ),
        migrations.DeleteModel(
            name='SaleAndCategory',
        ),
    ]
