# Generated by Django 4.0.5 on 2022-06-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_offerandcategory_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerandcategory',
            old_name='element_type',
            new_name='type',
        ),
    ]
