# Generated by Django 4.0.5 on 2022-06-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_rename_element_type_offerandcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerandcategory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
